**NUMPY** (numerical python)- Fundamental library

* Support for large, multi-dimensional arrays and matrices
* operation of mathematicall functions
* preprocessing



In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

2.0.2


In [ ]:
print(arr[0])

1


In [ ]:
print(arr[2] + arr[3])

7


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [ ]:
print('5th element on 2nd row: ', arr[1,4])

5th element on 2nd row:  10


In [ ]:
#slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5]) #here 5 is explicit

[2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


**data types in  NumPy**


* i - integer
* b - boolean
* u - unsigned int
* f - float
* c - complex float
* m - time delta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type(void)



In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('shape of array: ', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)


In [ ]:
import numpy as np
a = np.array([(1,2,3),(3,4,4)]) #2 dimensional array
print(a)
print(type(a)) #it is an n dimensional array
print(a.dtype) #each element of the array gets 64 bits

[[1 2 3]
 [3 4 4]]
<class 'numpy.ndarray'>
int64


In [ ]:
b = np.array([1,2,3])
print(a.ndim)
print(b.ndim) #tells the dimension of the array

2
1


In [ ]:
print(a.shape)
print(b.shape) #rows & columns

(2, 3)
(3,)


In [ ]:
a = np.array([(1,2,3),(3,4,4)], dtype='int16')
print(a.dtype)

int16


In [ ]:
print(a.itemsize)

2


In [ ]:
a = np.array([(1,2,3),(3,4,4)], dtype='int32')
print(a.itemsize) #no of bytes
print(a.size) #no of elements in the array

4
6


In [ ]:
print(a.size *a.itemsize)
print(a.nbytes) #both are same

24
24


In [ ]:
yay = np.arange(start = 1, stop = 10, step = 2)
#arange is alternative for array but it takes a given range and print the array
print(yay)

[1 3 5 7 9]


In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [ ]:
print(a[1,4])
a[0,-1]

12


np.int64(7)

In [ ]:
print(a[1, :])
print(a[:,5])

[ 8  9 10 11 12 13 14]
[ 6 13]


In [ ]:
print(a[0, 1:6:2])

[2 4 6]


In [ ]:
a[1,6] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]


In [ ]:
a[:, 2]= 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 20]]


In [ ]:
q = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(q)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(q[0,1,1])
print(q[:, 1, :])

4
[[3 4]
 [7 8]]


In [ ]:
#replace
q[:,1,:] = [9,9],[9,9]
q

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [9, 9]]])

#Initializing different types of arrays

In [ ]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
print(np.zeros((2,2,3)))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
print(np.ones((4,2,2), dtype='int32'))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [ ]:
print(np.full((2,2), 99, dtype='float32'))

[[99. 99.]
 [99. 99.]]


In [ ]:
print(np.full_like(q,7))

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [ ]:
print(np.random.rand(2,3))
print(np.random.random_sample(q.shape))

[[0.712962   0.89319034 0.08540648]
 [0.80627514 0.9445784  0.35605629]]
[[[0.65091019 0.31125992]
  [0.34406805 0.93991271]]

 [[0.13844548 0.89560957]
  [0.76113568 0.23881114]]]


In [ ]:
print(np.random.randint(7, size=(3,3)))
print(np.random.randint(-6,6, size=(2,2)))
print(np.random.randint(-6,6,2))

[[5 3 1]
 [2 1 1]
 [6 3 0]]
[[ 3 -4]
 [ 1 -2]]
[-5  4]


In [ ]:
print(np.identity(7, dtype='int16'))

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [ ]:
arr = np.array([1,2,3])
z = np.repeat(arr, 3, axis=0)
print(z)

[1 1 1 2 2 2 3 3 3]


In [ ]:
o=np.zeros([3,3])
print(o)
o[1:2]=9
print(o)
o[1]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [9. 9. 9.]
 [0. 0. 0.]]


array([9., 9., 9.])

#COPYING ARRAYS

In [ ]:
a = np.array([1,2,3])
b=a #a is created and then b is also pointing to same object, a copy is not getting created its the same object
print(b)
b
b[0]=100
print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]


In [ ]:
b = a.copy() #here the content of a is copied in b
print(a)
b[2]=90
print(b)
print(a)

[100   2   3]
[100   2  90]
[100   2   3]


#MATHEMATICS AND BROADCASTING

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+=2
print(a)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[3 4 5 6]
[5 6 7 8]
[1 2 3 4]
[ 6  8 10 12]
[1.5 2.  2.5 3. ]


In [ ]:
b = np.array([1,0,1,0])
print(a+b)

[4 4 6 6]


In [ ]:
print(a**2)

[ 9 16 25 36]


In [ ]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

#LINEAR ALGEBRA

In [ ]:
a = np.ones((2,3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

#STATISTICS

In [ ]:
stats=np.array([[5,2,3], [4,5,6]])
stats
print(np.min(stats))
print(np.max(stats))
print(np.min(stats, axis=1)) #it returns the new array with amx values from each row
print(np.max(stats, axis=0)) #it returns the new array with max vakues from each columns
sum(sum(stats))

2
6
[2 4]
[5 5 6]


np.int64(25)